name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build:prod
      - name: Upload build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/launchpad-js
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: dist
      - name: Fetch build
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: .
      - name: Commit build
        run: |
          git add --all
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add new version" -a
      - name: Push build
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
